# Generated by Django 2.0 on 2017-12-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostaweemvse', '0002_auto_20171210_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
